### PR TITLE
finish project

### PR DESCRIPTION
**Pull request by nyz83**
In this Pull Request (PR), I have completed the following tasks:

- Added a `.gitignore` file and added `node_modules` and `test.md`  to it.
- Set up linters for HTML and CSS.
- Updated my Readme file.
- Added .html and .css 
- Added test.md file

### CODE REVIEW

**Review by Rhaegar121 — CHANGES_REQUESTED** [review]
## STATUS: REQUIRES CHANGES 🚦 ⚠️ ♻️ 

Hi @Rhaegar121  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

close lady

## Highlights 💯 
- Descriptive Pull request summary ✔️
- Correct use of GitHub flow ✔️
- Good commit messages ✔️
- Professional Readme file ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Review by Rhaegar121 — COMMENTED** [review]
I think you might have misunderstood when installing the linters and forming the folder. The folder should be like this:
```
.github
- workflows
- - linters.yml
.hintrc
.stylelintrc.json
```
That means you have to manually create a .github folder and workflows is also a folder and inside that folder you have to create a new file called `linters.yml`. And inside that file, you can copy and paste the code from the provided source.

This is your current formation:
```
.hintrc
.stylelintrc.json
```
After changing that, you will see the GitHub action will work in your current pull request and you can check if the linters are passed or not.

Reference :

Screenshot (161)

**Comment by nyz83** [comment]
@Rhaegar121 I've addressed the feedback and made the necessary changes. Could you please re-review my pull request? Thank you!

**Comment by Rhaegar121** [comment]
Hi @nyz83, Congratulations, your .github folder set up is correct! But you still need to copy the code from the provided source as I highlighted in the screenshot.

Screenshot (162)

This is the code you needed to copy and paste in your `linters.yml` file:
```
name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Setup Lighthouse
        run: npm install -g @lhci/cli@0.11.x
      - name: Lighthouse Report
        run: lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=.
  webhint:
    name: Webhint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Setup Webhint
        run: |
          npm install --save-dev hint@7.x
          [ -f .hintrc ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.hintrc
      - name: Webhint Report
        run: npx hint .
  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Setup Stylelint
        run: |
          npm install --save-dev stylelint@13.x stylelint-scss@3.x stylelint-config-standard@21.x stylelint-csstree-validator@1.x
          [ -f .stylelintrc.json ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.stylelintrc.json
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"
  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
```

**Comment by nyz83** [comment]
@Rhaegar121 I've added the necessary codes for linters.yml file. Thank you for giving me your time.

**Comment by nyz83** [comment]
@Rhaegar121 I've fixed errors and all checks have passed. Thank you for giving me your time.

**Review by Rhaegar121 — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @nyz83 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Pull request merged**
